In [10]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

import warnings
warnings.filterwarnings('ignore')

iris = load_iris()

In [11]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,Y_train,Y_test = train_test_split(iris.data,iris.target,test_size=0.3)
lr = LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

0.9777777777777777

In [27]:
X_train,X_test,Y_train,Y_test = train_test_split(iris.data,iris.target,test_size=0.3)
svm = SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9555555555555556

In [28]:
X_train,X_test,Y_train,Y_test = train_test_split(iris.data,iris.target,test_size=0.3)
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9333333333333333

In [49]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [50]:
# for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
#     print(train_index,test_index)

In [51]:
# from sklearn.model_selection import StratifiedKFold
# folds = StratifiedKFold(n_splits=3)

In [52]:
from sklearn.model_selection import cross_val_score

In [53]:
cross_val_score(LogisticRegression(),iris.data,iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [54]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [55]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=kf)

array([0., 0., 0.])

In [59]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score,StratifiedKFold
from sklearn.linear_model import LogisticRegression
iris=load_iris()
X=iris.data
Y=iris.target
logreg=LogisticRegression()
stratifiedkf=StratifiedKFold(n_splits=5)
score=cross_val_score(logreg,X,Y,cv=stratifiedkf)
print("Cross Validation Scores are {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores are [0.96666667 1.         0.93333333 0.96666667 1.        ]
Average Cross Validation score :0.9733333333333334
